# Install Plugins
set -g @plugin 'tmux-plugins/tpm'

# Set Default Shell
set-option -g default-shell /bin/fish

# Rebind The Prefix
unbind C-b
set-option -g prefix ` 
bind ` send-prefix

# Bind Reload Config Key
bind r source-file ~/.config/tmux/tmux.conf \; refresh-client -S \; display-message "Configuration Reloaded"

# Copy to System Clipboard
bind -T copy-mode-vi 'y' send-keys -X begin-selection 

# Bind Movement Keys (Vim Keys)
bind h select-pane -R
bind j select-pane -D
bind k select-pane -U
bind l select-pane -L

# Bind Split
bind | split-window -h
bind - split-window -v

# Bind New Window Key
unbind c
bind n new-window

# Bind Kill Window
bind b kill-window

# Bind Kill Pane
bind x kill-pane

# Bind Kill TMUX Server
bind z kill-server

# Common Settings
set -g mouse on
set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ",*:Tc"
set -g default-command "${SHELL}"
set -g allow-passthrough on
set -g visual-activity off
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1

set -g status-position bottom 
set -g status-style "bg=default,fg=white"

setw -g window-status-format "#[fg=#a6adc8,bg=default]#W"            
setw -g window-status-current-format "#[bold]#[fg=#cba6f7,bg=default]#W"

set -g status-interval 1
set -g renumber-windows on

set -g focus-events on
set -g status-style bg=default
set -g status-justify absolute-centre
set -g status-interval 1
set -g renumber-windows on
set -g status-left ""
set -g status-right ""

# Initialize TMUX plugin manager
run '~/.config/tmux/plugins/tpm/tpm'
